#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Autostart

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill ~/.config/wallpaper.png
dunst &
polybar &
